Repository saucelabs/saucectl, pull requests merged in 2022-07, with the labels that each got.

#576 added rootdir flag
  internal/cmd/run/run.go
Labels: enhancement, playwright, testcafe, cypress

#578 Fix JSON Schema References
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1/subschema/common.schema.json
  api/v1alpha/framework/cypress.schema.json
  api/v1alpha/framework/espresso.schema.json
  api/v1alpha/framework/playwright.schema.json
  api/v1alpha/framework/puppeteer.schema.json
  api/v1alpha/framework/replay.schema.json
  api/v1alpha/framework/testcafe.schema.json
  api/v1alpha/framework/xcuitest.schema.json
  api/v1alpha/subschema/common.schema.json
Labels: bug

#579 Add release note template
  .github/release.yml
Labels: ignore-for-release

#581 [DEVX-1829] Fix path match issue for windows
  internal/fpath/file.go
Labels: bug

#586 Prevent early job termination for queued jobs
  internal/cmd/run/run.go
Labels: enhancement, playwright, testcafe, cypress, replay
