Repository saucelabs/saucectl, pull requests merged in 2022-10, with the labels that each got.

#612 Add us-east-4
  .github/workflows/test.yml
  .sauce/cypress-10.yml
  api/saucectl.schema.json
  api/v1alpha/subschema/sauce.schema.json
  internal/region/region.go
Labels: ignore-for-release

#614 Add regional restrictions
  internal/cmd/run/cypress.go
  internal/cmd/run/playwright.go
  internal/cmd/run/puppeteer.go
  internal/cmd/run/replay.go
  internal/cmd/run/testcafe.go
  internal/espresso/config.go
  internal/msg/errormsg.go
  internal/saucecloud/cloud.go
  internal/xcuitest/config.go
Labels: ignore-for-release

#616 [DEVX-1943] Return user-friendly err msg for storage 429 resp
  internal/appstore/appstore.go
  internal/storage/storage.go
Labels: enhancement

#621 [DEVX-1979] Add workers settings for playwright
  api/saucectl.schema.json
  api/v1alpha/framework/playwright.schema.json
  internal/cmd/run/playwright.go
  internal/playwright/config.go
Labels: playwright
