Repository saucelabs/saucectl, pull requests merged in 2022-08, with the labels that each got.

#589 Increase RDC timeout to accommodate large asset downloads
  internal/cmd/run/run.go
Labels: enhancement, espresso, xcuitest

#587 Add visibility configuration for tests on sauce
  api/saucectl.schema.json
  api/v1/subschema/sauce.schema.json
  api/v1alpha/subschema/sauce.schema.json
  internal/config/config.go
  internal/cypress/v1/config.go
  internal/cypress/v1alpha/config.go
  internal/espresso/config.go
  internal/job/starter.go
  internal/msg/errormsg.go
  internal/playwright/config.go
  internal/puppeteer/replay/config.go
  internal/saucecloud/cypress.go
  internal/saucecloud/espresso.go
  internal/saucecloud/playwright.go
  internal/saucecloud/replay.go
  internal/saucecloud/testcafe.go
  internal/testcafe/config.go
  internal/webdriver/webdriver.go
Labels: enhancement

#590 [DEVX-1813] Launch job by fail rate
  api/saucectl.schema.json
  api/v1/subschema/sauce.schema.json
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/run.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/config/config.go
  internal/cypress/suite/suite.go
  internal/cypress/suite/suite_test.go
  internal/cypress/v1/config.go
  internal/cypress/v1alpha/config.go
  internal/espresso/config.go
  internal/espresso/config_test.go
  internal/iam/iam.go
  internal/iam/user.go
  internal/insights/insights.go
  internal/insights/jobhistory.go
  internal/msg/errormsg.go
  internal/playwright/config.go
  internal/playwright/config_test.go
  internal/puppeteer/replay/config.go
  internal/puppeteer/replay/config_test.go
  internal/saucecloud/cloud.go
  internal/saucecloud/cypress.go
  internal/saucecloud/espresso.go
  internal/saucecloud/playwright.go
  internal/saucecloud/replay.go
  internal/saucecloud/testcafe.go
  internal/saucecloud/xcuitest.go
  internal/testcafe/config.go
  internal/testcafe/config_test.go
  internal/xcuitest/config.go
  internal/xcuitest/config_test.go
Labels: enhancement, playwright, testcafe, cypress, replay, espresso, xcuitest

#593 [DEVX-1813] Add launchOrder in segment
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/cypress/suite/suite.go
  internal/espresso/config.go
  internal/playwright/config.go
  internal/puppeteer/replay/config.go
  internal/testcafe/config.go
  internal/usage/tracker.go
  internal/xcuitest/config.go
Labels: enhancement

#592 Update cypress pipeline
  .github/workflows/test.yml
  .sauce/cypress-10.yml
Labels: ignore-for-release

#595 [DEVX-1856] Bump go to 1.19
  .github/workflows/release.yml
  .github/workflows/test.yml
  go.mod
  internal/apps/apps.go
  internal/saucecloud/xcuitest.go
Labels: ignore-for-release

#597 [DEVX-1842] Fix dependencies uploading with empty node_modules folder
  internal/saucecloud/cloud.go
  internal/saucecloud/cloud_test.go
Labels: bug, playwright, testcafe, cypress

#599 Enable additional linter rules
  .golangci.yml
  internal/apps/apps.go
  internal/framework/search.go
  internal/framework/search_test.go
  internal/saucecloud/cloud.go
Labels: ignore-for-release

#598 Run api-testing tests with saucectl
  .github/workflows/test.yml
  .sauce/apitest.yml
  api/global.schema.json
  api/saucectl.schema.json
  api/v1alpha/framework/apitest.schema.json
  internal/apitest/config.go
  internal/apitest/runner.go
  internal/apitesting/async.go
  internal/apitesting/client.go
  internal/apitesting/sync.go
  internal/cmd/run/apitest.go
  internal/cmd/run/run.go
  internal/report/table/table.go
  internal/resto/client.go
  internal/resto/client_test.go
  internal/saucecloud/cloud.go
  internal/tunnel/tunnel.go
Labels: enhancement

#602 Ask to overwrite creds if they already exist
  internal/cmd/configure/cmd.go
Labels: bug
