Repository saucelabs/saucectl, pull requests merged in 2023-03, with the labels that each got.

#715 Bump go to 1.20
  .github/workflows/release.yml
  .github/workflows/test.yml
  Dockerfile
  go.mod
Labels: enhancement

#721 fix: Correct linting errors reported by golangci-lint@1.52.0
  .github/workflows/test.yml
  .golangci.yml
  internal/archive/zip/zip.go
  internal/cmd/ini/common.go
  internal/docker/docker.go
Labels: ignore-for-release

#724 Add saucectl to chocolatey
  .github/workflows/release.yml
  .goreleaser.yml
Labels: enhancement

#728 Add select-suite for cucumber
  internal/cmd/run/cucumber.go
Labels: bug

#732 Fix node release
  .github/workflows/release.yml
  .goreleaser.yml
Labels: bug
