Repository saucelabs/saucectl, pull requests merged in 2023-12, with the labels that each got.

#863 fix: incomplete playwright init
  internal/cmd/ini/cmd.go
  internal/cmd/ini/initializer.go
  internal/cmd/ini/initializer_test.go
  internal/cmd/ini/playwright.go
Labels: bug

#864 chore!: remove deprecated new-cmd
  cmd/saucectl/saucectl.go
  internal/cmd/new/cmd.go
Labels: breaking-change

#865 ci: remove broken apif tests
  .sauce/apitest.yml
  tests/api/Flow Control/input.yaml
  tests/api/Flow Control/unit.yaml
Labels: ignore-for-release

#860 feat: add saucectl docker push cmd
  cmd/saucectl/saucectl.go
  go.mod
  go.sum
  internal/cmd/docker/cmd.go
  internal/cmd/docker/push.go
  internal/http/imagerunner.go
Labels: enhancement

#866 feat!: separate out init command
  cmd/saucectl/saucectl.go
  internal/cmd/ini/cmd.go
  internal/cmd/ini/cypress.go
  internal/cmd/ini/espresso.go
  internal/cmd/ini/imagerunner.go
  internal/cmd/ini/initializer.go
  internal/cmd/ini/initializer_test.go
  internal/cmd/ini/playwright.go
  internal/cmd/ini/testcafe.go
  internal/cmd/ini/xcuitest.go
Labels: breaking-change

#868 fix: init region requirement for no-prompt mode
  internal/cmd/ini/cmd.go
Labels: bug
