Repository saucelabs/saucectl, pull requests merged in 2023-11, with the labels that each got.

#848 feat: Add buildURL in JSON report
  internal/cmd/run/run.go
  internal/report/buildtable/buildtable.go
  internal/report/report.go
  internal/saucecloud/cloud.go
Labels: enhancement

#849 feat: Add JSON reporter for Sauce Orchestrate
  api/saucectl.schema.json
  api/v1alpha/framework/imagerunner.schema.json
  api/v1alpha/subschema/reporters.schema.json
  internal/cmd/run/imagerunner.go
  internal/http/resto.go
  internal/imagerunner/config.go
  internal/report/json/json.go
  internal/report/report.go
  internal/saucecloud/imagerunner.go
Labels: enhancement

#852 chore: Improve client instantiation
  internal/cmd/run/apitest.go
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/imagerunner.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/run.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
Labels: ignore-for-release

#855 feat!: Make region mandatory
  .github/workflows/test.yml
  internal/cmd/imagerunner/cmd.go
  internal/cmd/run/run.go
  internal/playwright/config_test.go
Labels: breaking-change

#857 fix: Better logging for timed out jobs
  internal/saucecloud/cloud.go
Labels: ignore-for-release

#854 feat: Support custom regions
  internal/region/region.go
Labels: ignore-for-release

#858 feat: Support regional credentials
  internal/cmd/run/apitest.go
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/imagerunner.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/region/region.go
  internal/region/region_test.go
Labels: ignore-for-release

#859 fix: app storage filename references for xcuitest simulators
  internal/apps/apps.go
  internal/apps/apps_test.go
  internal/saucecloud/cloud.go
Labels: bug, xcuitest

#862 chore: deprecate flag uploadTimeout
  internal/cmd/run/run.go
Labels: enhancement

#861 chore!: remove deprecated flag tunnel-id
  internal/cmd/run/run.go
Labels: breaking-change
