Repository saucelabs/saucectl, pull requests merged in 2023-05, with the labels that each got.

#763 Remove obsolete termination reason check
  internal/saucecloud/imagerunner.go
Labels: ignore-for-release

#764 Refactor files package
  internal/cmd/imagerunner/artifacts.go
  internal/cmd/storage/upload.go
  internal/fileio/temp.go
  internal/files/files.go
  internal/hashio/files.go
  internal/hashio/files_test.go
  internal/saucecloud/cloud.go
  internal/saucecloud/imagerunner.go
Labels: ignore-for-release

#765 Remove direct dependency pkg/errors
  go.mod
  internal/framework/search_test.go
Labels: ignore-for-release

#766 Remove unnecessary file check
  internal/apps/apps.go
  internal/apps/apps_test.go
  internal/msg/errormsg.go
  internal/msg/msg.go
Labels: enhancement

#761 APIF-1427 renames methods for uploading tests to the cloud
  internal/apitest/runner.go
  internal/apitest/runner_test.go
Labels: go

#767 Fix video skew
  internal/http/webdriver.go
Labels: bug

#769 Detect Gitpod environments
  internal/ci/ci.go
  internal/ci/ci_test.go
Labels: enhancement

#770 Add tunnel for image runner
  internal/imagerunner/imagerunner.go
  internal/saucecloud/imagerunner.go
Labels: enhancement

#771 Check tunnel availability for image runner
  internal/cmd/run/imagerunner.go
  internal/imagerunner/imagerunner.go
  internal/saucecloud/imagerunner.go
Labels: enhancement

#768 Update framework versions in JSON schema
  .github/workflows/test.yml
  .sauce/cypress-10.yml
  .sauce/playwright.yml
  .sauce/testcafe.yml
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1alpha/framework/cypress.schema.json
  api/v1alpha/framework/playwright.schema.json
  api/v1alpha/framework/testcafe.schema.json
Labels: documentation

#772 Add sharding for XCUITest
  api/saucectl.schema.json
  api/v1alpha/framework/xcuitest.schema.json
  internal/cmd/run/xcuitest.go
  internal/concurrency/concurrency.go
  internal/concurrency/concurrency_test.go
  internal/cucumber/config.go
  internal/cypress/v1/config.go
  internal/cypress/v1alpha/config.go
  internal/playwright/config.go
  internal/testcafe/config.go
  internal/xcuitest/config.go
  internal/xcuitest/config_test.go
Labels: enhancement

#773 Fix XCUITest sharding suite name
  internal/xcuitest/config.go
Labels: bug

#774 Optimize Project ID retrieval for APIT
  go.mod
  internal/apitest/config.go
  internal/apitest/runner.go
  internal/apitest/runner_test.go
Labels: enhancement

#775 Add resourceProfile for HTO
  api/saucectl.schema.json
  api/v1alpha/framework/imagerunner.schema.json
  internal/imagerunner/config.go
  internal/imagerunner/config_test.go
  internal/msg/errormsg.go
  internal/saucecloud/imagerunner.go
Labels: enhancement

#777 Add missing smartRetry in JSON schema
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1/subschema/common.schema.json
  api/v1alpha/framework/playwright-cucumberjs.schema.json
Labels: documentation

#780 Refactor APIT Test Result Collection
  internal/apitest/errors.go
  internal/apitest/runner.go
  internal/apitest/runner_test.go
  internal/http/apitester.go
Labels: enhancement

#783 Remove backtrace integration
  .github/workflows/docker-release.yml
  .github/workflows/release.yml
  .goreleaser.yml
  cmd/saucectl/saucectl.go
  go.mod
  go.sum
  internal/backtrace/backtrace.go
  internal/cmd/configure/cmd.go
  internal/cmd/ini/cmd.go
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/run.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/cmd/signup/cmd.go
  internal/setup/backtrace.go
Labels: ignore-for-release

#779 Add output for Github Job Summary
  internal/cmd/run/run.go
  internal/report/github/summary.go
Labels: enhancement

#782 Add Dry-Run for ImageRunner
  internal/imagerunner/config.go
  internal/saucecloud/cloud.go
  internal/saucecloud/cucumber.go
  internal/saucecloud/espresso.go
  internal/saucecloud/imagerunner.go
  internal/saucecloud/playwright.go
  internal/saucecloud/playwright_test.go
  internal/saucecloud/replay.go
  internal/saucecloud/testcafe.go
  internal/saucecloud/testcafe_test.go
  internal/saucecloud/xcuitest.go
Labels: enhancement

#784 Improve smart retry for mobile
  internal/espresso/config.go
  internal/junit/junit.go
  internal/msg/errormsg.go
  internal/saucecloud/retry/junitretrier.go
  internal/saucecloud/retry/junitretrier_test.go
Labels: enhancement

#785 Validate archive length
  internal/archive/zip/zip.go
  internal/archive/zip/zip_test.go
  internal/msg/msg.go
  internal/saucecloud/cloud.go
  internal/saucecloud/cloud_test.go
  internal/saucecloud/xcuitest.go
  internal/saucecloud/zip/archive.go
Labels: enhancement

#788 feat: improve fetching event for APItest
  go.mod
  go.sum
  internal/http/apitester.go
  internal/http/apitester_test.go
Labels: enhancement

#787 fix: Ensure app is a path before archiving
  internal/saucecloud/xcuitest.go
Labels: bug
