Repository saucelabs/saucectl, pull requests merged in 2023-06, with the labels that each got.

#786 feat: Increase robustness of uploads over network or service hiccups
  go.mod
  go.sum
  internal/cmd/storage/upload.go
  internal/http/appstore.go
  internal/http/appstore_test.go
  internal/multipartext/multipart.go
  internal/multipartext/seeker.go
  internal/multipartext/seeker_test.go
  internal/progress/progress.go
Labels: enhancement

#790 Add dry-run support for APITesting
  internal/apitest/config.go
  internal/apitest/runner.go
Labels: enhancement

#792 fix: Refine error msg for smart retry
  internal/msg/errormsg.go
Labels: documentation

#793 chore: Don't track usage against staging
  internal/cmd/apit/cmd.go
  internal/cmd/artifacts/cmd.go
  internal/cmd/imagerunner/cmd.go
  internal/cmd/jobs/cmd.go
  internal/cmd/run/apitest.go
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/imagerunner.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/cmd/storage/cmd.go
Labels: ignore-for-release

#796 chore: Set workload type when initing sauce config
  internal/cmd/ini/cmd.go
  internal/cmd/ini/imagerunner.go
  internal/cmd/ini/initializer.go
  internal/cmd/ini/initializer_test.go
Labels: enhancement

#797 Bump available framework version
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1alpha/framework/playwright.schema.json
  api/v1alpha/framework/testcafe.schema.json
Labels: documentation

#798 feat: Add saucectl configure list
  internal/cmd/configure/cmd.go
  internal/cmd/configure/list.go
  internal/credentials/credentials.go
  internal/credentials/credentials_test.go
  internal/iam/auth.go
Labels: enhancement

#799 fix: Handle empty credentials when listing credentials
  internal/cmd/configure/list.go
Labels: enhancement

#800 Add support for shardGrepEnabled for playwright
  api/saucectl.schema.json
  api/v1alpha/framework/playwright.schema.json
  internal/cmd/run/playwright.go
  internal/cypress/v1/config.go
  internal/cypress/v1alpha/config.go
  internal/msg/errormsg.go
  internal/playwright/code/parser.go
  internal/playwright/code/parser_test.go
  internal/playwright/config.go
  internal/playwright/grep/grep.go
  internal/playwright/grep/grep_test.go
Labels: enhancement

#801 junit.xml: Add support for smart retires
  internal/job/starter.go
  internal/junit/reporter.go
  internal/junit/reporter_test.go
  internal/report/report.go
  internal/saucecloud/cloud.go
Labels: bug
