Repository saucelabs/saucectl, pull requests merged in 2023-04, with the labels that each got.

#734 Add cmd to download artifacts of ImageRunner
  internal/archive/zip/zip.go
  internal/cmd/imagerunner/artifacts.go
  internal/cmd/imagerunner/cmd.go
  internal/files/files.go
  internal/http/imagerunner.go
  internal/imagerunner/imagerunner.go
  internal/saucecloud/imagerunner.go
Labels: enhancement

#739 Enforce order of imports
  .golangci.yml
  internal/apitest/runner_test.go
  internal/apps/apps_test.go
  internal/archive/tar/tar.go
  internal/archive/tar/tar_test.go
  internal/cmd/cmd.go
  internal/cmd/doctor/cmd.go
  internal/cmd/run/imagerunner.go
  internal/cmd/storage/download.go
  internal/cmd/storage/list.go
  internal/cypress/code/parser.go
  internal/cypress/code/parser_test.go
  internal/cypress/grep/parser.go
  internal/cypress/grep/parser_test.go
  internal/doctor/doctor.go
  internal/files/files_test.go
  internal/flags/binder.go
  internal/flags/exporter.go
  internal/flags/exporter_test.go
  internal/framework/search_test.go
  internal/http/apitester_test.go
  internal/http/errors.go
  internal/http/imagerunner_test.go
  internal/http/webdriver_test.go
  internal/imagerunner/config.go
  internal/jsonio/file_test.go
  internal/junit/reporter.go
  internal/junit/reporter_test.go
  internal/mocks/devices.go
  internal/mocks/docker.go
  internal/mocks/emulators.go
  internal/mocks/frameworks.go
  internal/mocks/job.go
  internal/notification/slack/slack.go
  internal/region/region_test.go
  internal/saucecloud/cypress.go
  internal/saucecloud/espresso_test.go
  internal/saucecloud/playwright_test.go
  internal/saucecloud/retry/basicretrier.go
  internal/saucecloud/retry/basicretrier_test.go
  internal/saucecloud/retry/junitretrier.go
  internal/saucecloud/retry/junitretrier_test.go
  internal/saucecloud/testcafe_test.go
  internal/saucecloud/xcuitest_test.go
  internal/streams/stream.go
  internal/tunnel/tunnel.go
  internal/viper/viper.go
  internal/yaml/file.go
  internal/yaml/file_test.go
Labels: ignore-for-release

#738 Add support for HTTP_PROXY
  internal/cmd/artifacts/download.go
  internal/cmd/artifacts/list.go
  internal/cmd/artifacts/upload.go
  internal/cmd/imagerunner/artifacts.go
  internal/cmd/imagerunner/logs.go
  internal/cmd/ini/cmd.go
  internal/cmd/run/run.go
  internal/http/apitester.go
  internal/http/appstore.go
  internal/http/client.go
  internal/http/github.go
  internal/http/insightsservice.go
  internal/http/proxy.go
  internal/http/testcomposer.go
  internal/http/userservice.go
  internal/http/webdriver.go
Labels: enhancement

#740 Remove Framework.Search() as this is unused
  internal/framework/framework.go
  internal/framework/search_test.go
  internal/http/testcomposer.go
  internal/http/testcomposer_test.go
  internal/mocks/frameworks.go
Labels: ignore-for-release

#742 Fix async mode
  .github/workflows/test.yml
  internal/saucecloud/cloud.go
Labels: bug

#741 Ensure PRs are labeled
  .github/workflows/pull-request-linter.yml
  .github/workflows/test.yml
Labels: ignore-for-release

#743 fix: ImageRunner errors management
  internal/cmd/artifacts/download.go
  internal/cmd/imagerunner/artifacts.go
  internal/cmd/imagerunner/logs.go
Labels: bug

#745 Add err handling for imagerunner artifacts download
  internal/http/imagerunner.go
Labels: bug

#746 fix: JunitRetrier: Check if map is nil before updating it
  internal/saucecloud/retry/junitretrier.go
  internal/saucecloud/retry/junitretrier_test.go
Labels: bug

#747 Use frameworks V2 API
  internal/cmd/ini/initializer.go
  internal/cmd/ini/initializer_test.go
  internal/framework/framework.go
  internal/framework/search_test.go
  internal/http/testcomposer.go
  internal/http/testcomposer_test.go
  internal/mocks/frameworks.go
Labels: enhancement

#744 ImageRunner: Add support for workflow type
  .sauce/imagerunner.yml
  api/saucectl.schema.json
  api/v1alpha/framework/imagerunner.schema.json
  internal/cmd/run/imagerunner.go
  internal/espresso/config_test.go
  internal/imagerunner/config.go
  internal/imagerunner/config_test.go
  internal/imagerunner/imagerunner.go
  internal/msg/errormsg.go
  internal/saucecloud/imagerunner.go
Labels: enhancement

#748 Remove saucectl doctor
  .github/workflows/test.yml
  cmd/saucectl/saucectl.go
  internal/cmd/doctor/cmd.go
  internal/doctor/doctor.go
Labels: breaking-change

#749 fix: smartRetry for XCUITest
  internal/saucecloud/retry/junitretrier.go
  internal/saucecloud/retry/junitretrier_test.go
Labels: bug

#752 Hide Usage when PreRun fails
  cmd/saucectl/saucectl.go
  internal/cmd/artifacts/cmd.go
  internal/cmd/artifacts/download.go
  internal/cmd/artifacts/list.go
  internal/cmd/artifacts/upload.go
  internal/cmd/completion/cmd.go
  internal/cmd/configure/cmd.go
  internal/cmd/imagerunner/artifacts.go
  internal/cmd/imagerunner/cmd.go
  internal/cmd/imagerunner/logs.go
  internal/cmd/ini/cmd.go
  internal/cmd/jobs/cmd.go
  internal/cmd/jobs/get.go
  internal/cmd/jobs/list.go
  internal/cmd/new/cmd.go
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/playwright.go
  internal/cmd/run/puppeteer.go
  internal/cmd/run/replay.go
  internal/cmd/run/run.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/cmd/signup/cmd.go
  internal/cmd/storage/cmd.go
  internal/cmd/storage/download.go
  internal/cmd/storage/list.go
  internal/cmd/storage/upload.go
Labels: documentation

#753 Remove support for puppeteer
  .github/workflows/test.yml
  .sauce/puppeteer.yml
  Makefile
  README.md
  api/global.schema.json
  api/saucectl.schema.json
  api/v1alpha/framework/puppeteer.schema.json
  cmd/saucectl/saucectl.go
  internal/cmd/ini/cmd.go
  internal/cmd/ini/common.go
  internal/cmd/ini/initializer.go
  internal/cmd/ini/initializer_test.go
  internal/cmd/ini/puppeteer.go
  internal/cmd/new/cmd.go
  internal/cmd/run/puppeteer.go
  internal/cmd/run/run.go
  internal/cmd/signup/cmd.go
  internal/docker/puppeteer.go
  internal/framework/search.go
  internal/http/testcomposer_test.go
  internal/msg/msg.go
  internal/puppeteer/config.go
Labels: breaking-change

#754 Remove support for Docker in init
  internal/cmd/ini/cmd.go
  internal/cmd/ini/common.go
  internal/cmd/ini/common_test.go
  internal/cmd/ini/cypress.go
  internal/cmd/ini/initializer.go
  internal/cmd/ini/initializer_test.go
  internal/cmd/ini/playwright.go
  internal/cmd/ini/testcafe.go
Labels: breaking-change

#755 cypress: Remove docker execution cypress
  .sauce/cypress-10.yml
  .sauce/cypress.yml
  Makefile
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1/subschema/common.schema.json
  api/v1/subschema/docker.schema.json
  api/v1alpha/framework/cypress.schema.json
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cypress/config.go
  internal/cypress/v1/config.go
  internal/cypress/v1/config_test.go
  internal/cypress/v1alpha/config.go
  internal/docker/cypress.go
Labels: breaking-change

#756 playwright: Remove docker execution
  .sauce/playwright.yml
  Makefile
  api/saucectl.schema.json
  api/v1alpha/framework/playwright.schema.json
  internal/cmd/run/playwright.go
  internal/docker/playwright.go
  internal/playwright/config.go
Labels: breaking-change

#757 playwright-cucumber: Remove docker execution
  api/saucectl.schema.json
  api/v1alpha/framework/playwright-cucumberjs.schema.json
  internal/cmd/run/cucumber.go
  internal/cucumber/config.go
  internal/docker/cucumber.go
Labels: breaking-change

#758 testcafe: Remove docker execution
  .golangci.yml
  .sauce/testcafe.yml
  Makefile
  api/saucectl.schema.json
  api/v1alpha/framework/testcafe.schema.json
  api/v1alpha/subschema/common.schema.json
  api/v1alpha/subschema/docker.schema.json
  internal/cmd/run/testcafe.go
  internal/docker/testcafe.go
  internal/testcafe/config.go
  internal/usage/tracker.go
Labels: breaking-change

#751 Add smart retry for js frameworks
  api/saucectl.schema.json
  api/v1alpha/framework/cypress.schema.json
  api/v1alpha/framework/playwright.schema.json
  api/v1alpha/framework/testcafe.schema.json
  api/v1alpha/subschema/common.schema.json
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/playwright.go
  internal/cmd/run/testcafe.go
  internal/config/config.go
  internal/cucumber/config.go
  internal/cucumber/config_test.go
  internal/cypress/config.go
  internal/cypress/v1/config.go
  internal/cypress/v1/config_test.go
  internal/cypress/v1alpha/config.go
  internal/cypress/v1alpha/config_test.go
  internal/espresso/config.go
  internal/job/starter.go
  internal/msg/errormsg.go
  internal/playwright/config.go
  internal/playwright/config_test.go
  internal/saucecloud/cloud.go
  internal/saucecloud/cloud_test.go
  internal/saucecloud/cucumber.go
  internal/saucecloud/cypress.go
  internal/saucecloud/cypress_test.go
  internal/saucecloud/espresso.go
  internal/saucecloud/playwright.go
  internal/saucecloud/retry/basicretrier_test.go
  internal/saucecloud/retry/junitretrier.go
  internal/saucecloud/retry/junitretrier_test.go
  internal/saucecloud/retry/project.go
  internal/saucecloud/retry/saucereportretrier.go
  internal/saucecloud/retry/saucereportretrier_test.go
  internal/saucecloud/testcafe.go
  internal/saucecloud/xcuitest.go
  internal/saucecloud/zip/archive.go
  internal/saucereport/saucereport.go
  internal/saucereport/saucereport_test.go
  internal/testcafe/config.go
  internal/testcafe/config_test.go
  internal/xcuitest/config.go
Labels: enhancement

#760 Add launchOrder for v1alpha in Schema
  api/saucectl.schema.json
  api/v1alpha/subschema/sauce.schema.json
Labels: bug

#759 docker: Remove support components
  .github/ISSUE_TEMPLATE/1-bug-report.md
  .golangci.yml
  CONTRIBUTING.md
  go.mod
  go.sum
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/run.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/config/config.go
  internal/docker/container.go
  internal/docker/container_test.go
  internal/docker/docker.go
  internal/docker/docker_test.go
  internal/dots/dots.go
  internal/mocks/docker.go
  internal/msg/errormsg.go
  internal/msg/msg.go
  internal/streams/in.go
  internal/streams/out.go
  internal/streams/stream.go
  tests/e2e/playwright-cucumberjs/.sauce/config.yml
Labels: breaking-change
