Repository saucelabs/saucectl, pull requests merged in 2023-08, with the labels that each got.

#814 Include directories in zip files
  internal/archive/zip/zip.go
  internal/archive/zip/zip_test.go
Labels: ignore-for-release

#816 fix: Fix Windows zip file
  internal/archive/zip/zip.go
Labels: bug

#817 feat: Retain file headers when zipping files
  internal/archive/zip/zip.go
Labels: enhancement

#818 chore: Bump e2e dependencies
  tests/e2e/playwright-cucumberjs/package-lock.json
  tests/e2e/playwright-cucumberjs/package.json
Labels: ignore-for-release

#820 fix: Set platformName for simulators
  .sauce/xcuitest.yml
  internal/xcuitest/config.go
Labels: xcuitest

#819 feat: Add additional testOptions for xcuitest
  api/saucectl.schema.json
  api/v1alpha/framework/xcuitest.schema.json
  internal/saucecloud/xcuitest.go
  internal/xcuitest/config.go
  internal/xcuitest/config_test.go
Labels: enhancement, xcuitest

#821 chore: Refactor junit package
  internal/cmd/run/run.go
  internal/junit/junit.go
  internal/report/junit/junit.go
  internal/report/junit/junit_test.go
  internal/saucecloud/cloud.go
  internal/saucecloud/cloud_test.go
  internal/saucecloud/retry/junitretrier.go
  internal/saucecloud/retry/junitretrier_test.go
Labels: ignore-for-release

#822 fix: Missing default otherApps
  internal/espresso/config.go
  internal/xcuitest/config.go
Labels: bug, xcuitest

#823 feat: Extend junit model
  internal/insights/testrun.go
  internal/insights/testrun_test.go
  internal/junit/junit.go
  internal/report/junit/junit_test.go
  internal/saucecloud/cloud.go
Labels: enhancement

#824 chore: junit separation of concerns
  internal/junit/junit.go
  internal/saucecloud/retry/junitretrier.go
Labels: ignore-for-release

#825 chore: Refactor attempt tracking
  internal/apitest/runner.go
  internal/job/starter.go
  internal/report/junit/junit.go
  internal/report/junit/junit_test.go
  internal/report/report.go
  internal/report/table/table.go
  internal/report/table/table_test.go
  internal/saucecloud/cloud.go
  internal/saucecloud/cloud_test.go
  internal/saucecloud/imagerunner.go
Labels: ignore-for-release

#827 chore: junit consolidation
  .sauce/cypress-10.yml
  .sauce/cypress.yml
  .sauce/espresso-env-var.yml
  .sauce/espresso.yml
  .sauce/playwright.yml
  .sauce/testcafe.yml
  internal/junit/junit.go
  internal/junit/junit_test.go
  internal/report/junit/junit.go
  internal/report/junit/junit_test.go
Labels: ignore-for-release

#826 feat: saucectl init for xcuitest on simulators
  api/saucectl.schema.json
  api/v1alpha/framework/xcuitest.schema.json
  internal/cmd/ini/cmd.go
  internal/cmd/ini/common.go
  internal/cmd/ini/common_test.go
  internal/cmd/ini/initializer.go
  internal/cmd/ini/initializer_test.go
  internal/cmd/ini/xcuitest.go
  internal/msg/errormsg.go
Labels: xcuitest

#828 feat: Add spotlight reporter
  api/saucectl.schema.json
  api/v1alpha/subschema/reporters.schema.json
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/playwright.go
  internal/cmd/run/run.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/config/config.go
  internal/cypress/config.go
  internal/cypress/v1/config.go
  internal/cypress/v1alpha/config.go
  internal/report/spotlight/spotlight.go
  internal/report/spotlight/spotlight_test.go
  internal/saucecloud/cloud.go
  internal/usage/tracker.go
Labels: enhancement
