Repository saucelabs/saucectl, pull requests merged in 2023-02, with the labels that each got.

#661 publish saucectl to Docker
  .github/workflows/docker-release.yml
  Dockerfile
Labels: ignore-for-release

#667 Fix docker doctor
  internal/docker/docker.go
Labels: bug

#668 Simplify docker smoke test
  .github/workflows/docker-release.yml
Labels: ignore-for-release

#673 Clean up artifact download logic
  internal/config/config.go
  internal/config/config_test.go
  internal/docker/container.go
  internal/saucecloud/cloud.go
  internal/saucecloud/imagerunner.go
Labels: ignore-for-release

#675 Set our own docker image version
  .github/workflows/docker-release.yml
Labels: ignore-for-release

#676 Stop generating UUID for test-runs api
  internal/insights/testrun.go
Labels: ignore-for-release

#677 Remove sauce cloud ASCII brand
  internal/cmd/run/run.go
  internal/msg/msg.go
Labels: enhancement

#678 Add CodeQL
  .github/workflows/codeql.yml
Labels: ignore-for-release

#679 Remove deprecated flag tunnel-parent
  internal/cmd/run/run.go
Labels: breaking-change

#680 Add env var for apitesting
  internal/apitest/config.go
  internal/apitest/runner.go
  internal/apitest/runner_test.go
  internal/apitesting/async.go
  internal/apitesting/async_test.go
Labels: enhancement

#681 Reduce memory footprint during uploads
  internal/appstore/appstore.go
  internal/appstore/appstore_test.go
  internal/saucecloud/cloud.go
  internal/saucecloud/cypress_test.go
  internal/saucecloud/espresso_test.go
  internal/saucecloud/xcuitest_test.go
  internal/storage/storage.go
Labels: enhancement

#682 Remove deprecated playwright flags
  internal/cmd/run/playwright.go
  internal/playwright/config.go
  internal/playwright/config_test.go
Labels: playwright, breaking-change

#683 Refactor imagerunner
  internal/cmd/run/run.go
  internal/http/imagerunner.go
Labels: ignore-for-release

#684 Refactor testcomposer
  internal/cmd/artifacts/cmd.go
  internal/cmd/ini/initializer.go
  internal/cmd/run/run.go
  internal/http/errors.go
  internal/http/testcomposer.go
  internal/http/testcomposer_test.go
  internal/saucecloud/artifactservice.go
Labels: ignore-for-release

#686 Refactor webdriver
  internal/cmd/run/run.go
  internal/http/testcomposer_test.go
  internal/http/webdriver.go
  internal/http/webdriver_test.go
Labels: ignore-for-release

#688 Refactor iam
  internal/cmd/jobs/cmd.go
  internal/cmd/run/run.go
  internal/http/userservice.go
  internal/iam/userservice.go
  internal/saucecloud/cloud.go
  internal/saucecloud/jobservice.go
Labels: ignore-for-release

#689 Refactor AppStore
  internal/apps/apps.go
  internal/cmd/run/run.go
  internal/cmd/storage/cmd.go
  internal/http/appstore.go
  internal/http/appstore_test.go
  internal/saucecloud/cloud.go
  internal/storage/storage.go
Labels: ignore-for-release

#690 Refactor resto
  internal/cmd/artifacts/cmd.go
  internal/cmd/ini/initializer.go
  internal/cmd/run/run.go
  internal/http/errors.go
  internal/http/resto.go
  internal/http/resto_test.go
  internal/saucecloud/artifactservice.go
Labels: ignore-for-release

#692 Refactor RDC
  internal/cmd/artifacts/cmd.go
  internal/cmd/ini/initializer.go
  internal/cmd/run/run.go
  internal/http/rdcservice.go
  internal/http/rdcservice_test.go
  internal/http/resto_test.go
  internal/http/testcomposer_test.go
  internal/http/webdriver_test.go
  internal/saucecloud/artifactservice.go
Labels: ignore-for-release

#696 Fix: Allow empty image credentials
  internal/imagerunner/imagerunner.go
  internal/saucecloud/imagerunner.go
Labels: bug

#697 Refactor insights
  internal/cmd/jobs/cmd.go
  internal/cmd/run/run.go
  internal/http/insightsservice.go
  internal/http/insightsservice_test.go
  internal/insights/client.go
  internal/insights/job.go
Labels: ignore-for-release

#699 Fix flaky signal test
  internal/saucecloud/cloud_test.go
Labels: ignore-for-release

#701 Add usage tracking to imagerunner
  internal/cmd/run/imagerunner.go
Labels: ignore-for-release

#702 Refactor Artifacts
  internal/cmd/artifacts/cmd.go
  internal/cmd/artifacts/download.go
  internal/cmd/artifacts/list.go
  internal/cmd/artifacts/upload.go
  internal/saucecloud/artifactservice.go
Labels: bug

#703 HTTP Cleanup
  internal/cmd/ini/initializer.go
  internal/cmd/jobs/cmd.go
  internal/cmd/run/run.go
  internal/cmd/storage/cmd.go
  internal/http/apitester.go
  internal/http/appstore.go
  internal/http/github.go
  internal/http/imagerunner.go
  internal/http/insightsservice.go
  internal/http/rdcservice.go
  internal/http/request.go
  internal/http/request_test.go
  internal/http/resto.go
  internal/http/testcomposer.go
  internal/http/userservice.go
  internal/http/webdriver.go
  internal/requesth/request.go
  internal/requesth/request_test.go
Labels: ignore-for-release

#704 Fix: Propagate last error after exhausting all retry attempts
  go.mod
  go.sum
  internal/http/rdcservice.go
  internal/http/rdcservice_test.go
  internal/http/resto.go
  internal/http/resto_test.go
Labels: bug

#706 Finalize Imagerunner states
  internal/imagerunner/imagerunner.go
  internal/report/table/table.go
Labels: enhancement

#707 Report the correct payload size when uploading app files
  internal/http/appstore.go
  internal/http/appstore_test.go
Labels: bug

#709 Refactor concurrency retrieval
  internal/cmd/ini/cmd.go
  internal/cmd/ini/initializer.go
  internal/cmd/ini/initializer_test.go
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/concurrency/concurrency.go
  internal/concurrency/concurrency_test.go
  internal/concurrency/reader.go
  internal/http/rdcservice.go
  internal/http/rdcservice_test.go
  internal/http/resto.go
  internal/http/userservice.go
  internal/iam/userservice.go
  internal/mocks/concurrency.go
  internal/mocks/userservice.go
  internal/saucecloud/cloud.go
  internal/saucecloud/cypress_test.go
  internal/saucecloud/jobservice.go
Labels: ignore-for-release

#710 Add imagerunner test to the pipeline
  .github/workflows/test.yml
  .sauce/imagerunner.yml
  tests/e2e/imagerunner/hello.txt
Labels: ignore-for-release

#712 Bump framework versions
  .sauce/cypress-10.yml
  .sauce/testcafe.yml
Labels: ignore-for-release

#713 Better retries for image runner
  internal/http/client.go
  internal/http/imagerunner.go
  internal/http/rdcservice.go
  internal/http/rdcservice_test.go
  internal/http/request.go
  internal/http/resto.go
  internal/http/resto_test.go
Labels: enhancement

#714 Refactor iam and credentials
  internal/cmd/configure/cmd.go
  internal/cmd/ini/cmd.go
  internal/cmd/ini/initializer.go
  internal/cmd/ini/initializer_test.go
  internal/cmd/run/run.go
  internal/credentials/credentials.go
  internal/credentials/credentials_test.go
  internal/http/imagerunner.go
  internal/http/insightsservice.go
  internal/http/insightsservice_test.go
  internal/http/testcomposer.go
  internal/http/testcomposer_test.go
  internal/http/userservice.go
  internal/http/webdriver.go
  internal/iam/auth.go
Labels: ignore-for-release
