Repository saucelabs/saucectl, pull requests merged in 2023-09, with the labels that each got.

#829 feat: Add latest frameworks version
  .sauce/cypress-10.yml
  .sauce/playwright.yml
  .sauce/testcafe.yml
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1alpha/framework/playwright.schema.json
  api/v1alpha/framework/testcafe.schema.json
Labels: enhancement

#830 fix: Incorrect serialization of RDC appSettings caused them to never take effect
  internal/http/rdcservice.go
  internal/job/starter.go
Labels: bug

#831 feat: Add storage delete command
  internal/cmd/storage/cmd.go
  internal/cmd/storage/delete.go
  internal/http/appstore.go
  internal/http/appstore_test.go
  internal/saucecloud/retry/saucereportretrier_test.go
  internal/storage/storage.go
Labels: enhancement

#834 feat: Enable env vars for xcuitest
  api/saucectl.schema.json
  api/v1alpha/framework/xcuitest.schema.json
  internal/cmd/run/run.go
  internal/http/webdriver.go
  internal/job/starter.go
  internal/saucecloud/xcuitest.go
  internal/xcuitest/config.go
Labels: enhancement, xcuitest

#835 chore: Use go 1.21
  .github/workflows/codeql.yml
  .github/workflows/docker-release.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  Dockerfile
  go.mod
Labels: enhancement

#836 fix: Support --env flag and root env vars simultaneously
  internal/apitest/config.go
  internal/cmd/run/run.go
  internal/cucumber/config.go
  internal/cypress/v1/config.go
  internal/cypress/v1alpha/config.go
  internal/imagerunner/config.go
  internal/playwright/config.go
  internal/testcafe/config.go
  internal/xcuitest/config.go
Labels: bug

#837 feat: add testApp in metadata for mobile tests
  internal/http/webdriver.go
  internal/job/starter.go
  internal/saucecloud/espresso.go
  internal/saucecloud/xcuitest.go
Labels: enhancement, espresso, xcuitest

#838 ci: remove dedicated env var e2e test
  .github/workflows/test.yml
  .sauce/espresso-env-var.yml
Labels: ignore-for-release
