Repository saucelabs/saucectl, pull requests merged in 2023-10, with the labels that each got.

#840 chore: Update json schema
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1alpha/framework/cypress.schema.json
  api/v1alpha/framework/playwright.schema.json
  api/v1alpha/framework/testcafe.schema.json
Labels: ignore-for-release

#841 feat: add async support for imagerunner
  internal/cmd/run/imagerunner.go
  internal/saucecloud/imagerunner.go
Labels: enhancement

#842 refactor: remove obsolete mode field
  internal/cucumber/config.go
  internal/cypress/suite/suite.go
  internal/cypress/v1/config.go
  internal/cypress/v1alpha/config.go
Labels: ignore-for-release

#843 fix: properly report imagerunner startup errors
  internal/http/imagerunner.go
  internal/imagerunner/imagerunner.go
  internal/saucecloud/imagerunner.go
Labels: bug

#844 fix: canonicalize service name correctly
  internal/imagerunner/utils.go
  internal/imagerunner/utils_test.go
Labels: bug

#845 fix: terminate idle connections
  internal/http/webdriver.go
Labels: bug

#847 feat: Support statusBarOverrideTime for XCUITest Sim
  api/saucectl.schema.json
  api/v1alpha/framework/xcuitest.schema.json
  internal/xcuitest/config.go
  internal/xcuitest/config_test.go
Labels: enhancement
