Repository saucelabs/saucectl, pull requests merged in 2023-01, with the labels that each got.

#650 Re-queue jobs asynchronously
  internal/saucecloud/cloud.go
Labels: bug

#651 Add pendo integration
  internal/segment/segment.go
Labels: ignore-for-release

#656 [DEVX-1825] Add saucectl jobs cmd
  cmd/saucectl/saucectl.go
  internal/cmd/jobs/cmd.go
  internal/cmd/jobs/get.go
  internal/cmd/jobs/job/reader.go
  internal/cmd/jobs/list.go
  internal/insights/insights.go
  internal/insights/job.go
  internal/job/job.go
  internal/mocks/insights.go
  internal/saucecloud/jobservice.go
Labels: enhancement
