Repository saucelabs/saucectl, pull requests merged in 2023-07, with the labels that each got.

#803 Update goreleaser config
  .goreleaser.yml
Labels: ignore-for-release

#804 Remove useless flag devX
  internal/http/webdriver.go
Labels: ignore-for-release

#805 Add support for Env / Defaults.Env for ImageRunner
  internal/imagerunner/config.go
Labels: enhancement

#802 Exclude specs matching .sauceignore content
  internal/cypress/v1/config.go
  internal/cypress/v1alpha/config.go
  internal/cypress/v1alpha/config_test.go
  internal/playwright/config.go
  internal/sauceignore/files.go
  internal/sauceignore/files_test.go
  internal/testcafe/config.go
  internal/testcafe/config_test.go
Labels: enhancement

#806 fix: Imagerunner workload type not propagated due to wrong case
  internal/imagerunner/imagerunner.go
Labels: bug

#807 docs: Describe additional test options for espresso
  api/saucectl.schema.json
  api/v1alpha/framework/espresso.schema.json
Labels: documentation, ignore-for-release

#808 Enhance check for resource profile
  api/saucectl.schema.json
  api/v1alpha/framework/imagerunner.schema.json
  internal/imagerunner/config.go
  internal/imagerunner/config_test.go
  internal/msg/errormsg.go
Labels: enhancement

#810 fix: Skip rendering JUnit&JSON reporters when running in async mode
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/run.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
Labels: bug

#813 feat: Allow additional runner metadata to be set by the user
  api/saucectl.schema.json
  api/v1alpha/framework/imagerunner.schema.json
  internal/imagerunner/config.go
  internal/saucecloud/imagerunner.go
Labels: enhancement

#811 Update Available Versions
  .sauce/cypress-10.yml
  .sauce/cypress.yml
  .sauce/playwright.yml
  .sauce/testcafe.yml
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1alpha/framework/cypress.schema.json
  api/v1alpha/framework/playwright.schema.json
  api/v1alpha/framework/testcafe.schema.json
Labels: enhancement, ignore-for-release

#812 chore: Refine generating JSON&JUint report
  internal/http/resto.go
  internal/report/json/json.go
  internal/report/report.go
  internal/saucecloud/cloud.go
Labels: bug
