Repository saucelabs/saucectl, pull requests merged in 2024-10, with the labels that each got.

#952 fix: Async mode should not retry jobs
  .github/workflows/test.yml
  .sauce/apitest.yml
  internal/saucecloud/cloud.go
Labels: bug

#953 build: choose your own gobin
  Makefile
Labels: ignore-for-release

#954 feat: support downloading network.har and crash.json
  internal/http/rdcservice.go
Labels: enhancement

#955 fix: respect --runner-version flag
  internal/saucecloud/cucumber.go
  internal/saucecloud/cypress.go
  internal/saucecloud/playwright.go
  internal/saucecloud/testcafe.go
Labels: bug

#956 refactor: espresso sharding
  .github/workflows/test.yml
  .sauce/testcafe.yml
  internal/espresso/config.go
  internal/saucecloud/espresso.go
Labels: ignore-for-release

#957 refactor: espresso sharding
  internal/saucecloud/espresso.go
  internal/saucecloud/espresso_test.go
Labels: ignore-for-release

#959 refactor: jobservice
  internal/artifacts/artifacts.go
  internal/cmd/artifacts/artifactservice.go
  internal/cmd/artifacts/cmd.go
  internal/cmd/artifacts/list.go
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/http/rdcservice.go
  internal/http/rdcservice_test.go
  internal/http/webdriver.go
  internal/http/webdriver_test.go
  internal/job/starter.go
  internal/mocks/build.go
  internal/mocks/download.go
  internal/mocks/insights.go
  internal/mocks/job.go
  internal/saucecloud/cloud.go
  internal/saucecloud/cloud_test.go
  internal/saucecloud/cypress_test.go
  internal/saucecloud/downloader/downloader.go
  internal/saucecloud/jobservice.go
  internal/saucecloud/jobservice_test.go
Labels: ignore-for-release

#960 tests: reduce test time
  internal/http/rdcservice_test.go
  internal/http/testcomposer_test.go
Labels: ignore-for-release

#961 refactor: consolidate job interfaces
  internal/cmd/artifacts/artifactservice.go
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/playwright.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/http/rdcservice.go
  internal/http/rdcservice_test.go
  internal/http/resto.go
  internal/http/resto_test.go
  internal/http/testcomposer_test.go
  internal/job/job.go
  internal/job/options.go
  internal/job/reader.go
  internal/job/stopper.go
  internal/job/writer.go
  internal/mocks/job.go
  internal/saucecloud/cloud.go
  internal/saucecloud/jobservice.go
  internal/saucecloud/jobservice_test.go
  internal/saucecloud/retry/junitretrier.go
  internal/saucecloud/retry/junitretrier_test.go
  internal/saucecloud/retry/saucereportretrier.go
  internal/saucecloud/retry/saucereportretrier_test.go
Labels: ignore-for-release

#962 refactor: builds
  internal/build/build.go
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/run.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/http/build.go
  internal/http/build_test.go
  internal/http/resto.go
  internal/http/resto_test.go
  internal/saucecloud/cloud.go
Labels: ignore-for-release

#963 refactor: job url propagation
  internal/cmd/artifacts/cmd.go
  internal/cmd/ini/initializer.go
  internal/cmd/run/apitest.go
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/imagerunner.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/http/client.go
  internal/http/rdcservice.go
  internal/http/rdcservice_test.go
  internal/http/resto.go
  internal/http/resto_test.go
  internal/http/webdriver.go
  internal/http/webdriver_test.go
  internal/job/job.go
  internal/mocks/job.go
  internal/saucecloud/cloud.go
  internal/saucecloud/jobservice.go
  internal/saucecloud/jobservice_test.go
  internal/saucecloud/retry/saucereportretrier_test.go
Labels: ignore-for-release

#965 refactor: redundant job url construction
  internal/saucecloud/cloud.go
Labels: ignore-for-release
