Repository saucelabs/saucectl, pull requests merged in 2024-05, with the labels that each got.

#908 fix: apply correct resource profile to service containers
  internal/imagerunner/config.go
Labels: bug

#909 build: Use Go 1.22
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  Dockerfile
  go.mod
Labels: enhancement

#910 ci: pipeline hygiene
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: ignore-for-release

#912 chore(reporting): Remove jobs data from usage collection
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/usage/tracker.go
Labels: ignore-for-release

#913 feat: Use progress bar to display docker output
  go.mod
  go.sum
  internal/cmd/docker/push.go
Labels: enhancement

#914 feat: expand package.json files in npm.dependencies
  internal/human/bytes.go
  internal/human/bytes_test.go
  internal/saucecloud/zip/archive.go
  internal/saucecloud/zip/archive_test.go
Labels: enhancement

#915 chore(schema): add latest versions
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1alpha/framework/playwright.schema.json
  api/v1alpha/framework/testcafe.schema.json
Labels: ignore-for-release
