Repository saucelabs/saucectl, pull requests merged in 2024-09, with the labels that each got.

#943 fix: Should download artifacts when no retries
  internal/job/job.go
  internal/mocks/download.go
  internal/saucecloud/cloud.go
  internal/saucecloud/cloud_test.go
  internal/saucecloud/cypress_test.go
  internal/saucecloud/downloader/downloader.go
  internal/saucecloud/downloader/downloader_test.go
  internal/saucecloud/jobservice.go
Labels: bug

#945 refactor: Make test-composer HTTP client retryable
  internal/http/testcomposer.go
  internal/http/testcomposer_test.go
Labels: enhancement

#946 refactor: Extract framework validation
  internal/saucecloud/cucumber.go
  internal/saucecloud/cypress.go
  internal/saucecloud/playwright.go
  internal/saucecloud/testcafe.go
Labels: enhancement

#947 refactor: Extract framework EOL and removal notice
  internal/msg/msg.go
  internal/saucecloud/cloud.go
  internal/saucecloud/cucumber.go
  internal/saucecloud/cypress.go
  internal/saucecloud/playwright.go
  internal/saucecloud/testcafe.go
Labels: enhancement

#944 feat: Support global node
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1/subschema/common.schema.json
  api/v1alpha/framework/playwright-cucumberjs.schema.json
  api/v1alpha/framework/playwright.schema.json
  api/v1alpha/framework/testcafe.schema.json
  api/v1alpha/subschema/common.schema.json
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/playwright.go
  internal/cmd/run/testcafe.go
  internal/cucumber/config.go
  internal/cypress/config.go
  internal/cypress/v1/config.go
  internal/framework/framework.go
  internal/framework/search_test.go
  internal/http/testcomposer.go
  internal/http/webdriver.go
  internal/job/starter.go
  internal/mocks/frameworks.go
  internal/playwright/config.go
  internal/runtime/runtime.go
  internal/runtime/runtime_test.go
  internal/saucecloud/cucumber.go
  internal/saucecloud/cypress.go
  internal/saucecloud/playwright.go
  internal/saucecloud/testcafe.go
  internal/testcafe/config.go
  internal/usage/tracker.go
Labels: enhancement

#948 chore: Update deprecated tunnel configs
  internal/http/rdcservice.go
  internal/http/webdriver.go
  internal/job/starter.go
  internal/saucecloud/cloud.go
  internal/saucecloud/cucumber.go
  internal/saucecloud/cypress.go
  internal/saucecloud/espresso.go
  internal/saucecloud/playwright.go
  internal/saucecloud/replay.go
  internal/saucecloud/testcafe.go
  internal/saucecloud/xcuitest.go
Labels: enhancement

#949 feat: Capture sharding types and options
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/playwright.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/cucumber/config.go
  internal/cypress/config.go
  internal/cypress/v1/config.go
  internal/espresso/config.go
  internal/playwright/config.go
  internal/testcafe/config.go
  internal/usage/tracker.go
  internal/xcuitest/config.go
Labels: enhancement

#950 build: Use go 1.23
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  Dockerfile
  go.mod
Labels: enhancement

#951 chore: Update schema with new frameworks
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1alpha/framework/playwright.schema.json
Labels: ignore-for-release
