Repository saucelabs/saucectl, pull requests merged in 2024-06, with the labels that each got.

#916 fix: reporters v1 api schema
  api/saucectl.schema.json
  api/v1/subschema/reporters.schema.json
Labels: bug

#917 feat: ARM simulator support for xcuitest
  api/saucectl.schema.json
  api/v1alpha/framework/xcuitest.schema.json
  internal/config/config.go
  internal/flags/simulator.go
  internal/http/webdriver.go
  internal/job/starter.go
  internal/saucecloud/cloud.go
  internal/saucecloud/espresso.go
  internal/saucecloud/xcuitest.go
Labels: enhancement, xcuitest

#920 chore: Monthly framework update
  .sauce/cypress-10.yml
  .sauce/playwright.yml
  .sauce/testcafe.yml
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1alpha/framework/playwright.schema.json
  api/v1alpha/framework/testcafe.schema.json
Labels: ignore-for-release
