Repository saucelabs/saucectl, pull requests merged in 2024-01, with the labels that each got.

#832 feat: Support setting reporters for TestCafe
  .sauce/testcafe.yml
  api/saucectl.schema.json
  api/v1alpha/framework/testcafe.schema.json
  internal/cmd/run/testcafe.go
  internal/testcafe/config.go
Labels: enhancement

#870 chore: enable testcafe iOS tests
  .sauce/testcafe.yml
Labels: ignore-for-release

#871 refactor: dead code removal
  internal/archive/zip/zip.go
  internal/cmd/ini/common.go
  internal/cmd/ini/common_test.go
  internal/fpath/file.go
  internal/fpath/file_test.go
  internal/framework/framework.go
  internal/framework/framework_test.go
  internal/msg/msg.go
  internal/saucecloud/cypress.go
  internal/saucecloud/cypress_test.go
  internal/saucecloud/espresso.go
  internal/saucecloud/espresso_test.go
  internal/sauceignore/matcher.go
  internal/sauceignore/matcher_test.go
  internal/usage/tracker.go
Labels: ignore-for-release

#872 chore: Enhance Logging for Tunnel-Related Processes
  internal/apitest/runner.go
  internal/saucecloud/cloud.go
  internal/saucecloud/imagerunner.go
  internal/tunnel/tunnel.go
Labels: enhancement

#873 fix: Fix smart retry in XCUITest simulator test
  internal/cmd/run/xcuitest.go
  internal/saucecloud/retry/junitretrier.go
  internal/saucecloud/retry/junitretrier_test.go
Labels: bug

#875 chore: update supported framework versions in schema
  .github/workflows/test.yml
  .sauce/cypress-10.yml
  .sauce/playwright.yml
  .sauce/testcafe.yml
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1alpha/framework/playwright.schema.json
  api/v1alpha/framework/testcafe.schema.json
  tests/e2e/playwright-cucumberjs/.sauce/config.yml
Labels: ignore-for-release

#876 ci: optimize test pipeline
  .github/workflows/codeql.yml
  .github/workflows/docker-release.yml
  .github/workflows/pull-request-linter.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  README.md
Labels: ignore-for-release

#877 fix!: correctly scope flag
  internal/cmd/imagerunner/cmd.go
  internal/cmd/imagerunner/logs.go
Labels: bug, breaking-change

#878 feat: Add saucectl imagerunner stop cli
  internal/cmd/imagerunner/cmd.go
  internal/cmd/imagerunner/stop.go
Labels: enhancement

#879 refactor: improve imagerunner cloudevent handling
  internal/cmd/docker/cmd.go
  internal/cmd/imagerunner/cmd.go
  internal/cmd/imagerunner/logs.go
  internal/cmd/run/imagerunner.go
  internal/http/imagerunner.go
  internal/imagerunner/async.go
  internal/imagerunner/errors.go
  internal/saucecloud/imagerunner.go
Labels: ignore-for-release

#880 feat: Add cli to list imagerunner containers
  internal/cmd/imagerunner/cmd.go
  internal/cmd/imagerunner/list.go
  internal/http/imagerunner.go
Labels: enhancement

#881 fix: Switch to using fmt.Println
  internal/cmd/artifacts/list.go
  internal/cmd/artifacts/upload.go
  internal/cmd/configure/cmd.go
  internal/cmd/imagerunner/artifacts.go
  internal/cmd/ini/common.go
  internal/cmd/ini/imagerunner.go
  internal/cmd/jobs/get.go
  internal/cmd/jobs/list.go
  internal/cmd/storage/delete.go
  internal/cmd/storage/list.go
Labels: ignore-for-release
