Repository saucelabs/saucectl, pull requests merged in 2024-07, with the labels that each got.

#921 ci: upgrade actions/cache@v4
  .github/workflows/release.yml
Labels: ignore-for-release

#922 build: Use GoReleaser v2
  .github/workflows/release.yml
  .github/workflows/test.yml
  .goreleaser.yml
Labels: ignore-for-release

#924 fix: sauceignore pattern matching on windows
  internal/sauceignore/files.go
  internal/sauceignore/matcher.go
Labels: bug

#925 feat!: drop support for cypress v1alpha
  api/global.schema.json
  api/saucectl.schema.json
  api/v1alpha/framework/cypress.schema.json
  internal/cmd/ini/cypress.go
  internal/cypress/config.go
  internal/cypress/v1alpha/config.go
  internal/cypress/v1alpha/config_test.go
  internal/cypress/v1alpha/native.go
  internal/cypress/v1alpha/native_test.go
Labels: breaking-change

#926 feat: Support TestCafe esm flag
  api/saucectl.schema.json
  api/v1alpha/framework/testcafe.schema.json
  internal/cmd/run/testcafe.go
  internal/testcafe/config.go
Labels: enhancement

#927 chore: Remove condition that denies using tunnels in US-East
  internal/espresso/config.go
  internal/msg/errormsg.go
  internal/xcuitest/config.go
Labels: enhancement, espresso, xcuitest, go

#929 chore: Monthly framework update
  .sauce/cypress-10.yml
  .sauce/playwright.yml
  .sauce/testcafe.yml
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1alpha/framework/playwright.schema.json
  api/v1alpha/framework/testcafe.schema.json
Labels: ignore-for-release

#931 chore: Improve retryablehttp client
  internal/http/client.go
  internal/http/rdcservice.go
  internal/http/resto.go
Labels: enhancement
