Repository saucelabs/saucectl, pull requests merged in 2024-02, with the labels that each got.

#884 feat: attempt to stop rdc jobs on timeout
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/http/rdcservice.go
  internal/saucecloud/cloud.go
  internal/saucecloud/cloud_test.go
  internal/saucecloud/jobservice.go
Labels: enhancement, espresso, xcuitest

#885 refactor: job model
  internal/cmd/jobs/cmd.go
  internal/cmd/jobs/get.go
  internal/cmd/jobs/job/reader.go
  internal/cmd/jobs/list.go
  internal/http/insightsservice.go
  internal/http/insightsservice_test.go
  internal/http/rdcservice.go
  internal/http/rdcservice_test.go
  internal/http/resto.go
  internal/http/resto_test.go
  internal/insights/insights.go
  internal/insights/testrun.go
  internal/insights/testrun_test.go
  internal/job/job.go
  internal/mocks/insights.go
  internal/saucecloud/cloud.go
  internal/saucecloud/cypress_test.go
  internal/saucecloud/jobservice.go
Labels: ignore-for-release

#887 fix: junit retry regression for xcuitests in rdc
  internal/saucecloud/retry/junitretrier.go
  internal/saucecloud/retry/junitretrier_test.go
Labels: bug, xcuitest

#888 ci: setup go before running codeql
  .github/workflows/codeql.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: ignore-for-release

#886 build: add workflow to auto bump version
  .github/workflows/bump.yml
Labels: ignore-for-release

#889 fix: Don't try to download assets and logs if none are available
  internal/imagerunner/imagerunner.go
  internal/saucecloud/imagerunner.go
Labels: bug

#890 ci: update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ignore-for-release
