Repository saucelabs/saucectl, pull requests merged in 2024-08, with the labels that each got.

#932 feat: skip smart retry on errored jobs
  internal/cucumber/config.go
  internal/cypress/v1/config.go
  internal/msg/errormsg.go
  internal/playwright/config.go
  internal/saucecloud/cloud.go
  internal/saucecloud/cloud_test.go
  internal/saucecloud/retry/junitretrier.go
  internal/saucecloud/retry/junitretrier_test.go
  internal/saucecloud/retry/saucereportretrier.go
  internal/saucereport/saucereport.go
  internal/testcafe/config.go
Labels: enhancement

#933 feat: Tag aware sharding for cucumber-playwright
  api/saucectl.schema.json
  api/v1alpha/framework/playwright-cucumberjs.schema.json
  go.mod
  go.sum
  internal/cucumber/config.go
  internal/cucumber/tag/matcher.go
  internal/cucumber/tag/matcher_test.go
Labels: enhancement, playwright

#935 fix!: Update npm.strictSSL behavior
  .goreleaser.yml
  internal/cmd/docker/push.go
  internal/cmd/ini/initializer_test.go
  internal/cmd/run/cypress.go
  internal/cmd/run/playwright.go
  internal/cmd/run/run.go
  internal/cmd/run/testcafe.go
  internal/config/config.go
  internal/cypress/config.go
  internal/cypress/v1/config.go
  internal/http/proxy.go
Labels: breaking-change

#936 refactor: Encapsulate artifact downloading
  internal/cmd/artifacts/cmd.go
  internal/cmd/ini/initializer.go
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/http/rdcservice.go
  internal/http/rdcservice_test.go
  internal/http/resto.go
  internal/saucecloud/downloader/downloader.go
  internal/saucecloud/downloader/downloader_test.go
Labels: ignore-for-release

#937 feat: Add option to download matching artifacts for all job attempts
  api/saucectl.schema.json
  api/v1/subschema/artifacts.schema.json
  api/v1alpha/subschema/artifacts.schema.json
  internal/cmd/run/run.go
  internal/config/config.go
  internal/job/job.go
  internal/mocks/download.go
  internal/saucecloud/cloud.go
  internal/saucecloud/cloud_test.go
  internal/saucecloud/cypress_test.go
  internal/saucecloud/downloader/downloader.go
  internal/saucecloud/downloader/downloader_test.go
  internal/saucecloud/jobservice.go
Labels: enhancement

#940 feat: Support shard by scenario
  api/saucectl.schema.json
  api/v1alpha/framework/playwright-cucumberjs.schema.json
  internal/cucumber/config.go
  internal/cucumber/scenario/scenario.go
  internal/cucumber/tag/matcher.go
Labels: enhancement

#941 chore: Framework updates
  .sauce/cypress-10.yml
  .sauce/playwright.yml
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1alpha/framework/playwright.schema.json
  api/v1alpha/framework/testcafe.schema.json
Labels: ignore-for-release
