Repository saucelabs/saucectl, pull requests merged in 2024-12, with the labels that each got.

#988 chore: Add latest frameworks to schema
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1alpha/framework/playwright.schema.json
Labels: ignore-for-release

#989 feat: Shard xcuitest suite by testList
  api/saucectl.schema.json
  api/v1alpha/framework/xcuitest.schema.json
  internal/xcuitest/config.go
  internal/xcuitest/config_test.go
Labels: xcuitest

#990 feat: cancellable project uploads and job commands
  internal/cmd/jobs/get.go
  internal/cmd/jobs/list.go
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/http/rdcservice_test.go
  internal/http/webdriver_test.go
  internal/saucecloud/cloud.go
  internal/saucecloud/cloud_test.go
  internal/saucecloud/cucumber.go
  internal/saucecloud/cypress.go
  internal/saucecloud/espresso.go
  internal/saucecloud/playwright.go
  internal/saucecloud/replay.go
  internal/saucecloud/retry/basicretrier.go
  internal/saucecloud/retry/basicretrier_test.go
  internal/saucecloud/retry/junitretrier.go
  internal/saucecloud/retry/junitretrier_test.go
  internal/saucecloud/retry/retrier.go
  internal/saucecloud/retry/saucereportretrier.go
  internal/saucecloud/retry/saucereportretrier_test.go
  internal/saucecloud/testcafe.go
  internal/saucecloud/xcuitest.go
Labels: enhancement

#991 feat: greatly improve cancellability
  internal/apitest/runner.go
  internal/cmd/apit/deletefile.go
  internal/cmd/apit/downloadfile.go
  internal/cmd/apit/get.go
  internal/cmd/apit/getsnippet.go
  internal/cmd/apit/getvariable.go
  internal/cmd/apit/listfiles.go
  internal/cmd/apit/setsnippet.go
  internal/cmd/apit/setvariable.go
  internal/cmd/apit/uploadfile.go
  internal/cmd/apit/vault.go
  internal/cmd/artifacts/artifactservice.go
  internal/cmd/artifacts/download.go
  internal/cmd/artifacts/list.go
  internal/cmd/artifacts/upload.go
  internal/cmd/docker/push.go
  internal/cmd/imagerunner/artifacts.go
  internal/cmd/imagerunner/list.go
  internal/cmd/imagerunner/logs.go
  internal/cmd/imagerunner/stop.go
  internal/cmd/ini/cmd.go
  internal/cmd/ini/initializer.go
  internal/cmd/ini/initializer_test.go
  internal/cmd/run/apitest.go
  internal/cmd/run/imagerunner.go
  internal/http/testcomposer.go
  internal/http/testcomposer_test.go
  internal/job/job.go
  internal/mocks/job.go
  internal/saucecloud/cloud.go
  internal/saucecloud/cucumber.go
  internal/saucecloud/cypress.go
  internal/saucecloud/espresso.go
  internal/saucecloud/imagerunner.go
  internal/saucecloud/jobservice.go
  internal/saucecloud/playwright.go
  internal/saucecloud/replay.go
  internal/saucecloud/retry/saucereportretrier_test.go
  internal/saucecloud/testcafe.go
  internal/saucecloud/xcuitest.go
  internal/tunnel/tunnel.go
Labels: enhancement

#992 refactor: imagerunner global context
  internal/saucecloud/imagerunner.go
Labels: ignore-for-release

#993 feat: cancellable apitest
  internal/apitest/runner.go
  internal/apitest/runner_test.go
  internal/cmd/run/apitest.go
Labels: enhancement

#994 fix: ensure screenshots are recognized artifacts
  internal/http/resto.go
Labels: bug
