Repository saucelabs/saucectl, pull requests merged in 2024-11, with the labels that each got.

#966 chore: Always warn user of npm registry deprecation
  internal/config/config.go
  internal/config/config_test.go
  internal/cucumber/config.go
  internal/cypress/v1/config.go
  internal/playwright/config.go
  internal/testcafe/config.go
Labels: enhancement

#968 refactor: no err on worker pool creation
  internal/saucecloud/cloud.go
  internal/saucecloud/cucumber.go
  internal/saucecloud/cypress.go
  internal/saucecloud/espresso.go
  internal/saucecloud/playwright.go
  internal/saucecloud/replay.go
  internal/saucecloud/testcafe.go
  internal/saucecloud/xcuitest.go
Labels: ignore-for-release

#967 chore: Monthly framework update
  .sauce/cypress-10.yml
  .sauce/playwright.yml
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1alpha/framework/playwright.schema.json
  api/v1alpha/framework/testcafe.schema.json
Labels: ignore-for-release

#964 feat: Add config to use package-lock.json for dependency installation
  api/saucectl.schema.json
  api/v1/subschema/npm.schema.json
  internal/config/config.go
  internal/config/config_test.go
  internal/cucumber/config.go
  internal/cypress/v1/config.go
  internal/playwright/config.go
  internal/testcafe/config.go
Labels: enhancement

#969 fix: add usePackageLock for v1alpha schema
  api/saucectl.schema.json
  api/v1alpha/subschema/npm.schema.json
Labels: ignore-for-release

#970 refactor: Organize file details for uploading archives
  internal/cmd/storage/upload.go
  internal/http/apitester.go
  internal/http/appstore.go
  internal/http/appstore_test.go
  internal/multipartext/multipart.go
  internal/saucecloud/cloud.go
  internal/saucecloud/espresso.go
  internal/saucecloud/retry/saucereportretrier.go
  internal/saucecloud/retry/saucereportretrier_test.go
  internal/saucecloud/xcuitest.go
  internal/storage/storage.go
Labels: enhancement

#972 feat: cancellable storage interactions
  cmd/saucectl/saucectl.go
  internal/cmd/storage/delete.go
  internal/cmd/storage/download.go
  internal/cmd/storage/list.go
  internal/cmd/storage/upload.go
  internal/http/appstore.go
  internal/http/appstore_test.go
  internal/ioctx/ioctx.go
  internal/ioctx/ioctx_test.go
  internal/saucecloud/cloud.go
  internal/saucecloud/retry/saucereportretrier.go
  internal/saucecloud/retry/saucereportretrier_test.go
  internal/storage/storage.go
Labels: enhancement

#973 fix: track package lock usage
  internal/usage/tracker.go
Labels: enhancement

#974 deps: fix go mod tidy
  go.mod
  go.sum
Labels: dependencies

#975 chore: Bump Cypress & TestCafe version
  .github/workflows/test.yml
  .golangci.yml
  .sauce/cypress-10.yml
  .sauce/testcafe.yml
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1alpha/framework/testcafe.schema.json
  internal/cmd/docker/push.go
  internal/http/resto_test.go
  internal/multipartext/seeker.go
Labels: ignore-for-release

#976 refactor: variadic functions for telemetry settings
  cmd/saucectl/saucectl.go
  internal/cmd/apit/cmd.go
  internal/cmd/apit/deletefile.go
  internal/cmd/apit/downloadfile.go
  internal/cmd/apit/get.go
  internal/cmd/apit/getsnippet.go
  internal/cmd/apit/getvariable.go
  internal/cmd/apit/listfiles.go
  internal/cmd/apit/setsnippet.go
  internal/cmd/apit/setvariable.go
  internal/cmd/apit/uploadfile.go
  internal/cmd/artifacts/cmd.go
  internal/cmd/artifacts/download.go
  internal/cmd/artifacts/list.go
  internal/cmd/artifacts/upload.go
  internal/cmd/configure/cmd.go
  internal/cmd/docker/push.go
  internal/cmd/imagerunner/artifacts.go
  internal/cmd/imagerunner/cmd.go
  internal/cmd/imagerunner/list.go
  internal/cmd/imagerunner/logs.go
  internal/cmd/imagerunner/stop.go
  internal/cmd/ini/cypress.go
  internal/cmd/ini/espresso.go
  internal/cmd/ini/imagerunner.go
  internal/cmd/ini/playwright.go
  internal/cmd/ini/testcafe.go
  internal/cmd/ini/xcuitest.go
  internal/cmd/jobs/cmd.go
  internal/cmd/jobs/get.go
  internal/cmd/jobs/list.go
  internal/cmd/run/apitest.go
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/imagerunner.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/cmd/storage/cmd.go
  internal/cmd/storage/delete.go
  internal/cmd/storage/download.go
  internal/cmd/storage/list.go
  internal/cmd/storage/upload.go
  internal/segment/segment.go
  internal/usage/tracker.go
  internal/usage/usage.go
Labels: ignore-for-release

#977 refactor: telemetry package consolidation
  cmd/saucectl/saucectl.go
  internal/cmd/apit/cmd.go
  internal/cmd/apit/deletefile.go
  internal/cmd/apit/downloadfile.go
  internal/cmd/apit/get.go
  internal/cmd/apit/getsnippet.go
  internal/cmd/apit/getvariable.go
  internal/cmd/apit/listfiles.go
  internal/cmd/apit/setsnippet.go
  internal/cmd/apit/setvariable.go
  internal/cmd/apit/uploadfile.go
  internal/cmd/artifacts/cmd.go
  internal/cmd/artifacts/download.go
  internal/cmd/artifacts/list.go
  internal/cmd/artifacts/upload.go
  internal/cmd/configure/cmd.go
  internal/cmd/docker/push.go
  internal/cmd/imagerunner/artifacts.go
  internal/cmd/imagerunner/cmd.go
  internal/cmd/imagerunner/list.go
  internal/cmd/imagerunner/logs.go
  internal/cmd/imagerunner/stop.go
  internal/cmd/ini/cypress.go
  internal/cmd/ini/espresso.go
  internal/cmd/ini/imagerunner.go
  internal/cmd/ini/playwright.go
  internal/cmd/ini/testcafe.go
  internal/cmd/ini/xcuitest.go
  internal/cmd/jobs/cmd.go
  internal/cmd/jobs/get.go
  internal/cmd/jobs/list.go
  internal/cmd/run/apitest.go
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/imagerunner.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/cmd/storage/cmd.go
  internal/cmd/storage/delete.go
  internal/cmd/storage/download.go
  internal/cmd/storage/list.go
  internal/cmd/storage/upload.go
  internal/usage/client.go
Labels: ignore-for-release

#978 feat!: remove Slack notification integration
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/run.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/config/config.go
  internal/config/config_test.go
  internal/cucumber/config.go
  internal/cypress/config.go
  internal/cypress/v1/config.go
  internal/espresso/config.go
  internal/http/testcomposer.go
  internal/http/testcomposer_test.go
  internal/notification/slack/service.go
  internal/notification/slack/slack.go
  internal/notification/slack/slack_test.go
  internal/playwright/config.go
  internal/puppeteer/replay/config.go
  internal/testcafe/config.go
  internal/usage/usage.go
  internal/xcuitest/config.go
Labels: breaking-change

#980 fix: Log tunnel and region once
  internal/apitest/runner.go
  internal/cmd/run/apitest.go
  internal/cmd/run/cucumber.go
  internal/cmd/run/cypress.go
  internal/cmd/run/espresso.go
  internal/cmd/run/imagerunner.go
  internal/cmd/run/playwright.go
  internal/cmd/run/replay.go
  internal/cmd/run/testcafe.go
  internal/cmd/run/xcuitest.go
  internal/saucecloud/cloud.go
  internal/saucecloud/imagerunner.go
Labels: ignore-for-release

#983 fix: Cucumber formatOptions should be an object
  api/saucectl.schema.json
  api/v1alpha/framework/playwright-cucumberjs.schema.json
Labels: ignore-for-release

#984 feat: rename CI tags
  internal/ci/ci.go
  internal/insights/testrun.go
Labels: enhancement

#985 fix: Make sure job errors are always printed
  internal/saucecloud/cloud.go
Labels: bug
