Repository saucelabs/saucectl, pull requests merged in 2025-07, with the labels that each got.

#1035 [INT-367] add testcafe ARM support
  .sauce/testcafe.yml
  api/saucectl.schema.json
  api/v1alpha/framework/testcafe.schema.json
  internal/saucecloud/testcafe.go
  internal/testcafe/config.go
Labels: enhancement

#1039 [INT-367] testcafe: fix invalid armRequired type
  api/saucectl.schema.json
  api/v1alpha/framework/testcafe.schema.json
Labels: bug, ignore-for-release

#1041 SauceCTL Framework update
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1alpha/framework/playwright.schema.json
  api/v1alpha/framework/testcafe.schema.json
Labels: ignore-for-release
