Repository saucelabs/saucectl, pull requests merged in 2025-01, with the labels that each got.

#996 feat: improve interrupt handling
  internal/http/rdcservice.go
  internal/http/rdcservice_test.go
  internal/http/resto.go
  internal/http/resto_test.go
  internal/job/job.go
  internal/mocks/job.go
  internal/saucecloud/cloud.go
  internal/saucecloud/cloud_test.go
  internal/saucecloud/cucumber.go
  internal/saucecloud/cypress.go
  internal/saucecloud/espresso.go
  internal/saucecloud/jobservice.go
  internal/saucecloud/jobservice_test.go
  internal/saucecloud/playwright.go
  internal/saucecloud/replay.go
  internal/saucecloud/retry/saucereportretrier.go
  internal/saucecloud/retry/saucereportretrier_test.go
  internal/saucecloud/testcafe.go
  internal/saucecloud/xcuitest.go
Labels: enhancement

#998 feat: support instrumentation capabilities
  api/saucectl.schema.json
  api/v1/subschema/common.schema.json
  api/v1alpha/subschema/common.schema.json
  internal/cmd/run/espresso.go
  internal/cmd/run/xcuitest.go
  internal/config/config.go
  internal/job/options.go
  internal/saucecloud/espresso.go
  internal/saucecloud/xcuitest.go
Labels: enhancement

#999 fix: incorrect espresso and xcuitest flags
  api/saucectl.schema.json
  api/v1/subschema/common.schema.json
  api/v1alpha/framework/espresso.schema.json
  api/v1alpha/framework/xcuitest.schema.json
  api/v1alpha/subschema/common.schema.json
  internal/cmd/run/espresso.go
  internal/cmd/run/xcuitest.go
  internal/config/config.go
  internal/job/options.go
  internal/saucecloud/xcuitest.go
Labels: enhancement

#1001 deps: bump go-git@v5.13.1
  go.mod
  go.sum
Labels: dependencies

#1002 fix: updated description of instrumentation capabilities
  api/saucectl.schema.json
  api/v1alpha/framework/espresso.schema.json
  api/v1alpha/framework/xcuitest.schema.json
  internal/cmd/run/espresso.go
  internal/cmd/run/xcuitest.go
  internal/saucecloud/espresso.go
  internal/saucecloud/xcuitest.go
Labels: documentation
