Repository saucelabs/saucectl, pull requests merged in 2025-05, with the labels that each got.

#1022 chore: Remove EOL'd imagerunner support
  .github/workflows/test.yml
  .sauce/imagerunner.yml
  api/global.schema.json
  api/saucectl.schema.json
  api/v1alpha/framework/imagerunner.schema.json
  cmd/saucectl/saucectl.go
  internal/cmd/docker/cmd.go
  internal/cmd/docker/push.go
  internal/cmd/imagerunner/artifacts.go
  internal/cmd/imagerunner/cmd.go
  internal/cmd/imagerunner/list.go
  internal/cmd/imagerunner/logs.go
  internal/cmd/imagerunner/stop.go
  internal/cmd/ini/cmd.go
  internal/cmd/ini/common.go
  internal/cmd/ini/imagerunner.go
  internal/cmd/ini/initializer.go
  internal/cmd/ini/initializer_test.go
  internal/cmd/run/imagerunner.go
  internal/cmd/run/run.go
  internal/http/cloudevents.go
  internal/http/imagerunner.go
  internal/http/imagerunner_test.go
  internal/imagerunner/cloudevents.go
  internal/imagerunner/config.go
  internal/imagerunner/config_test.go
  internal/imagerunner/errors.go
  internal/imagerunner/imagerunner.go
  internal/imagerunner/utils.go
  internal/imagerunner/utils_test.go
  internal/msg/errormsg.go
  internal/report/report.go
  internal/report/spotlight/spotlight.go
  internal/report/table/table.go
  internal/saucecloud/imagerunner.go
Labels: deprecation

#1027 [INT-186] update supported framework version lists
  api/saucectl.schema.json
  api/v1/framework/cypress.schema.json
  api/v1alpha/framework/playwright.schema.json
Labels: ignore-for-release

#1031 [INT-186] Playwright version 1.52.2 => 1.52.0
  api/saucectl.schema.json
  api/v1alpha/framework/playwright.schema.json
Labels: bug, ignore-for-release

#1034 [no-ticket] [e2e] use latest playwright version
  tests/e2e/playwright-cucumberjs/.sauce/config.yml
Labels: bug

#1033 [INT-168] playwright: escape test names before passing them to grep
  internal/playwright/config.go
Labels: bug
